const championsData = [
    { name: "Airi", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13001.jpg", skins: [
            { skinName: "Thích khách", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13001.jpg" },
            { skinName: "Ninja xanh lá", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13002.jpg" },
            { skinName: "Quái xế công nghệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13003.jpg" },
            { skinName: "Cấm vệ nguyệt tộc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13004.jpg" },
            { skinName: "Kiemono", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13005.jpg" },
            { skinName: "Bạch Kiemono", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13006.jpg" },
            { skinName: "Phó kiếm đạo", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13007.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13008.jpg" },
            { skinName: "Mỵ hồ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13009.jpg" },
            { skinName: "Đặc công tử điệp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13010.jpg" },
            { skinName: "Bích Hải thánh nữ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13011.jpg" },
            { skinName: "Lễ hội mùa xuân", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13012.jpg" },
            { skinName: "Thánh nữ Xiêm La", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13013.jpg" },
            { skinName: "Thứ nguyên Vệ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13015.jpg" },
            { skinName: "Ninja ẩm thực", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13017.jpg" },
            { skinName: "Búp bê Mộng mị", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13018.jpg" },
            { skinName: "Quản lý tài năng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13019.jpg" }
        ] },
    { name: "Allain", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53701.jpg", skins: [
            { skinName: "Hắc kiếm sĩ Kirito", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53701.jpg" },
            { skinName: "Kirito", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53702.jpg" },
            { skinName: "Tuyết sơn song kiếm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53703.jpg" },
            { skinName: "Thần mặt trời", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53704.jpg" },
            { skinName: "Bạch kiếm sĩ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53705.jpg" },
            { skinName: "Hạo Thiên Khuyển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53706.jpg" },
            { skinName: "Tình yêu nổi loạn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53707.jpg" },
            { skinName: "Lân sư Vũ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53708.jpg" },
            { skinName: "Cẩm y vệ - Xích Hổ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53709.jpg" }
        ] },
    { name: "Aoi", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53601.jpg", skins: [
            { skinName: "Sát thủ đô thị", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53601.jpg" },
            { skinName: "Hoàng kim công chúa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53602.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53604.jpg" },
            { skinName: "Lam Hải quận chúa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53605.jpg" },
            { skinName: "Tiểu thư Mafia", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53606.jpg" },
            { skinName: "Sát thủ Dạ Ưng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53608.jpg" },
            { skinName: "Quán Quân", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53609.jpg" },
            { skinName: "Bách thú triều Long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53611.jpg" },
            { skinName: "Mikasa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53612.jpg" }
        ] },
    { name: "Arduin", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12601.jpg", skins: [
            { skinName: "Cận vệ hoàng gia", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12601.jpg" },
            { skinName: "Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12602.jpg" },
            { skinName: "Tà linh hiệp sỹ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12603.jpg" },
            { skinName: "Chiến binh cổ đại", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12604.jpg" },
            { skinName: "Đường vào tim em", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12605.jpg" },
            { skinName: "Bạch vệ chiến giáp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12606.jpg" },
            { skinName: "Organ cổ quái", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12607.jpg" },
            { skinName: "Ngạo Hổ Hàn Đao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12608.jpg" },
            { skinName: "Nhà vô địch", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12609.jpg" },
            { skinName: "Cự thần Biển Mây", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12610.jpg" }
        ] },
    { name: "Bijan", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54801.jpg", skins: [
            { skinName: "Chiến binh sa mạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54801.jpg" },
            { skinName: "Hoàng Kim cơ giáp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54802.jpg" },
            { skinName: "Đập vỡ Cây đàn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54803.jpg" },
            { skinName: "Kình thiên Long Kỵ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54804.jpg" },
            { skinName: "Lữ Hành Thời Không", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54805.jpg" },
            { skinName: "Giai điệu Giáng Sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54806.jpg" }
        ] },
    { name: "Billow", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59901.jpg", skins: [
            { skinName: "Thiên Tướng - Độ Ách", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59901.jpg" },
            { skinName: "T-Rex Bất Bại", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59902.jpg" }
        ] },
    { name: "Biron", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59701.jpg", skins: [
            { skinName: "Võ sĩ Giác đấu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59701.jpg" },
            { skinName: "Yuji Itadori", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59702.jpg" }
        ] },
    { name: "Bolt Baron", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59801.jpg", skins: [
            { skinName: "Lôi vệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59801.jpg" },
            { skinName: "Thiên Phủ - Tư Mệnh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/59802.jpg" }
        ] },
    { name: "Capheny", class: "xa-thu", className: "Xạ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52401.jpg", skins: [
            { skinName: "Hầu gái", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52401.jpg" },
            { skinName: "Thần tượng âm nhạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52402.jpg" },
            { skinName: "Toán Hóa Sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52403.jpg" },
            { skinName: "Kimono", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52404.jpg" },
            { skinName: "Siêu cấp tin tặc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52405.jpg" },
            { skinName: "Phi hành gia", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52406.jpg" },
            { skinName: "Harley Quinn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52407.jpg" },
            { skinName: "Quân nhạc Mildar", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52408.jpg" },
            { skinName: "Tử đinh hương", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52410.jpg" },
            { skinName: "Vua trò chơi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52411.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52412.jpg" },
            { skinName: "Huyết phong", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52413.jpg" },
            { skinName: "Càn Nguyên Điện Chủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52414.jpg" },
            { skinName: "Bugcat Assemble", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52415.jpg" },
            { skinName: "Hoa Linh Lan", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52416.jpg" }
        ] },
    { name: "Cresht", class: "dau-si", className: "Đỡ Đòn", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17101.jpg", skins: [
            { skinName: "Thợ sửa cáp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17101.jpg" },
            { skinName: "Cá cắn cáp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17102.jpg" },
            { skinName: "Đại sư sushi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17103.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17104.jpg" },
            { skinName: "Bách tướng Lão tam", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17106.jpg" },
            { skinName: "Caesar bão tố", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17107.jpg" },
            { skinName: "Eren Jaegar", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/17108.jpg" }
        ] },
    { name: "Dolia", class: "phap-su", className: "Hỗ Trợ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15901.jpg", skins: [
            { skinName: "Hoa tiêu đại dương", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15901.jpg" },
            { skinName: "Môn đồ tập sự", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15902.jpg" },
            { skinName: "Nhật Ký Tình Yêu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15903.jpg" },
            { skinName: "Huyễn Ngọc Nhân Ngư", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15904.jpg" },
            { skinName: "Mã Khởi Thiên Ca", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15905.jpg" }
        ] },
    { name: "Eland'orr", class: "xa-thu", className: "Xạ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19901.jpg", skins: [
            { skinName: "Soái tặc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19901.jpg" },
            { skinName: "Phi vụ thế kỷ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19902.jpg" },
            { skinName: "Học viện Carano", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19903.jpg" },
            { skinName: "Siêu thám tử", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19904.jpg" },
            { skinName: "Chú ong bay cao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19905.jpg" },
            { skinName: "Tuxedo Mask", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19906.jpg" },
            { skinName: "Uyên Ương mộng điệp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19907.jpg" },
            { skinName: "Mộng Giới Thần Chủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19908.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19909.jpg" }
        ] },
    { name: "Elsu", class: "xa-thu", className: "Xạ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19601.jpg", skins: [
            { skinName: "Cảnh vệ thảo nguyên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19601.jpg" },
            { skinName: "Mafia", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19602.jpg" },
            { skinName: "Guitar tình ái", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19603.jpg" },
            { skinName: "Chiến binh bóng tối", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19604.jpg" },
            { skinName: "Sứ giả tận thế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19605.jpg" },
            { skinName: "Tuyết ưng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19606.jpg" },
            { skinName: "Xạ thủ tinh linh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19607.jpg" },
            { skinName: "Trấn Thiên phi hồ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19609.jpg" },
            { skinName: "Hỏa diệm Chu Tước", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19611.jpg" },
            { skinName: "Tuyệt ảnh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19612.jpg" },
            { skinName: "DJ <Siêu Đẳng>", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19613.jpg" },
            { skinName: "Xạ Thần Mộng Giới", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19614.jpg" }
        ] },
    { name: "Florentino", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52101.jpg", skins: [
            { skinName: "Vũ kiếm sư", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52101.jpg" },
            { skinName: "Giám sát tinh Hệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52102.jpg" },
            { skinName: "Kiếm sĩ Olympic", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52103.jpg" },
            { skinName: "Thần thoại Hy Lạp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52104.jpg" },
            { skinName: "Seven", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52105.jpg" },
            { skinName: "Tà long kiếm sĩ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52106.jpg" },
            { skinName: "Xứ sở thần tiên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52107.jpg" },
            { skinName: "Bá vương Âm nhạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52108.jpg" },
            { skinName: "Hisoka", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52110.jpg" },
            { skinName: "Hỏa diệm Thần long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52111.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52112.jpg" },
            { skinName: "Kỷ Nguyên Hổ Phách", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52113.jpg" }
        ] },
    { name: "Gildur", class: "phap-su", className: "Đấu Sĩ/Trợ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10801.jpg", skins: [
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10801.jpg" },
            { skinName: "Phượt thủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10802.jpg" },
            { skinName: "Đại gia học viện", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10803.jpg" },
            { skinName: "Đại võ sư", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10804.jpg" },
            { skinName: "Thuyền trưởng râu bạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10805.jpg" },
            { skinName: "Bác học thiên tài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10806.jpg" },
            { skinName: "Phù thủy Ba Tư", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10807.jpg" },
            { skinName: "Xích Long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10809.jpg" },
            { skinName: "PASULOL", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10811.jpg" }
        ] },
    { name: "Hayate", class: "xa-thu", className: "Xạ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13201.jpg", skins: [
            { skinName: "Bạch ảnh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13201.jpg" },
            { skinName: "Chiến binh trăng khuyết", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13202.jpg" },
            { skinName: "Ngân lang", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13203.jpg" },
            { skinName: "Tử thần vũ trụ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13204.jpg" },
            { skinName: "Quỷ diện", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13205.jpg" },
            { skinName: "Kim ưng sát thủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13206.jpg" },
            { skinName: "Bạch lang", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13207.jpg" },
            { skinName: "Bạch vô thường", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13208.jpg" },
            { skinName: "Bóng người dưới trăng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13209.jpg" },
            { skinName: "Tu Di thánh đế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13210.jpg" },
            { skinName: "Mãnh hổ kim cang", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13211.jpg" },
            { skinName: "Thống soái Dạ Ưng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13212.jpg" },
            { skinName: "Siêu đạo chích Kid", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13213.jpg" },
            { skinName: "Đầu bếp Yakitori", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13214.jpg" }
        ] },
    { name: "Heino", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/56301.jpg", skins: [
            { skinName: "Nhật Ký Tình Yêu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/56301.jpg" },
            { skinName: "Scout Regiment", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/56302.jpg" }
        ] },
    { name: "Keera", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53101.jpg", skins: [
            { skinName: "Y tá lạ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53101.jpg" },
            { skinName: "Học viện Carano", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53102.jpg" },
            { skinName: "Sát thủ bí ngô", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53103.jpg" },
            { skinName: "Thủy thủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53104.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53105.jpg" },
            { skinName: "Nezuko Kamado", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53107.jpg" },
            { skinName: "Nghệ sĩ Graffiti", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53109.jpg" },
            { skinName: "Hồ điệp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53110.jpg" },
            { skinName: "Môn đồ Xảo quyệt", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53111.jpg" },
            { skinName: "Quán quân", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53112.jpg" },
            { skinName: "Yêu Thần Nekomata", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53113.jpg" }
        ] },
    { name: "Lauriel", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14101.jpg", skins: [
            { skinName: "Đọa lạc thiên sứ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14101.jpg" },
            { skinName: "Hỏa phượng hoàng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14102.jpg" },
            { skinName: "Phù thủy bí ngô", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14103.jpg" },
            { skinName: "Thánh quang sứ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14104.jpg" },
            { skinName: "Hoa khôi giáng sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14105.jpg" },
            { skinName: "Lạc thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14106.jpg" },
            { skinName: "Tinh vân sứ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14107.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14108.jpg" },
            { skinName: "Thiên sứ công nghệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14109.jpg" },
            { skinName: "Phi Thiên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14110.jpg" },
            { skinName: "Thứ nguyên vệ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14111.jpg" },
            { skinName: "Nữ vương học đường", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14114.jpg" },
            { skinName: "Đôi cánh Nguyệt thực", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14115.jpg" },
            { skinName: "Nữ vương học đường", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14116.jpg" },
            { skinName: "Vũ khúc miêu ảnh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14117.jpg" },
            { skinName: "Thiên nữ Dạ Ưng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14118.jpg" },
            { skinName: "Mã Đằng Cửu Thế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/14120.jpg" }
        ] },
    { name: "Liliana", class: "phap-su", className: "Pháp Sư/Trợ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51001.jpg", skins: [
            { skinName: "Hồ quý phi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51001.jpg" },
            { skinName: "Thần tượng âm nhạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51002.jpg" },
            { skinName: "Nguyệt mị ly", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51003.jpg" },
            { skinName: "Tiểu thơ anh đào", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51004.jpg" },
            { skinName: "Tân nguyệt mị ly", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51005.jpg" },
            { skinName: "Nữ thần F1", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51006.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51007.jpg" },
            { skinName: "Thủy thủ hồ ly", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51008.jpg" },
            { skinName: "WaVe", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51009.jpg" },
            { skinName: "Lưu thủy Thần long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51013.jpg" },
            { skinName: "Thần hổ Xiêm La", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51014.jpg" },
            { skinName: "Ma Pháp Tối Thượng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51015.jpg" }
        ] },
    { name: "Lorion", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53901.jpg", skins: [
            { skinName: "Chiến giáp hắc ám", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53901.jpg" },
            { skinName: "Hỏa vân tà thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53902.jpg" },
            { skinName: "Quân vương bóng tối", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53903.jpg" },
            { skinName: "Quân vương ánh sáng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53904.jpg" },
            { skinName: "Giáo chủ tinh hệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53905.jpg" }
        ] },
    { name: "Marja", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12101.jpg", skins: [
            { skinName: "Lam Hải yêu hậu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12101.jpg" },
            { skinName: "Linh xà tư tế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12102.jpg" },
            { skinName: "Hỏa ngọc nữ vương", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12103.jpg" },
            { skinName: "Yêu nữ săn mồi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12104.jpg" },
            { skinName: "Chủ hôn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12105.jpg" },
            { skinName: "Phù Quang Mạc Ảnh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12106.jpg" },
            { skinName: "Hi Phi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12107.jpg" }
        ] },
    { name: "Murad", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13101.jpg", skins: [
            { skinName: "Thợ săn tiền thưởng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13101.jpg" },
            { skinName: "M-TP Thần tượng học đường", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13102.jpg" },
            { skinName: "Đồ thần đao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13103.jpg" },
            { skinName: "Siêu việt", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13104.jpg" },
            { skinName: "Thiên tài sân cỏ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13105.jpg" },
            { skinName: "Điệp viên Anubis", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13106.jpg" },
            { skinName: "Đặc dị", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13107.jpg" },
            { skinName: "Siêu việt 2.0", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13108.jpg" },
            { skinName: "Chí tôn thần kiếm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13109.jpg" },
            { skinName: "Dược sĩ tình yêu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13110.jpg" },
            { skinName: "Byakuya Kuchiki", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13111.jpg" },
            { skinName: "Zenitsu Agatsuma", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13112.jpg" },
            { skinName: "Thích khách sa mạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13113.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13114.jpg" },
            { skinName: "Huyết hỏa cuồng đồ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13115.jpg" },
            { skinName: "Tuyệt thế thần binh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13116.jpg" },
            { skinName: "Chiến binh đồ chơi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13117.jpg" },
            { skinName: "Thiên Luân Kiếm Thánh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13118.jpg" },
            { skinName: "Thần Pháo Hoa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13119.jpg" }
        ] },
    { name: "Ngộ Không", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16701.jpg", skins: [
            { skinName: "Đạo tặc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16701.jpg" },
            { skinName: "Hỏa nhãn kim tinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16702.jpg" },
            { skinName: "Siêu việt", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16703.jpg" },
            { skinName: "Ngộ khá trẩu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16704.jpg" },
            { skinName: "Siêu việt 2.0", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16705.jpg" },
            { skinName: "Đặc vụ băng hầu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16706.jpg" },
            { skinName: "Nhóc tì bá đạo", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16707.jpg" },
            { skinName: "Tề Thiên ma hầu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16708.jpg" },
            { skinName: "Cổ thần Ai Cập", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16709.jpg" },
            { skinName: "Tân niên Võ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16710.jpg" },
            { skinName: "Thần Giáp Xích Diễm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16711.jpg" },
            { skinName: "Tề Thiên Võ Thánh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16712.jpg" },
            { skinName: "Đại náo văn phòng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16713.jpg" }
        ] },
    { name: "Omen", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50601.jpg", skins: [
            { skinName: "Sĩ quan viễn chinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50601.jpg" },
            { skinName: "Ám tử đao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50602.jpg" },
            { skinName: "Quỷ nguyệt tướng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50603.jpg" },
            { skinName: "Đao phủ tận thế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50604.jpg" },
            { skinName: "Chiến binh trăng khuyết", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50605.jpg" },
            { skinName: "Thuyền trưởng hải tặc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50606.jpg" },
            { skinName: "Nhạc sĩ huyền thoại", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50607.jpg" },
            { skinName: "Quái Kiệt Guitar", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50608.jpg" },
            { skinName: "Huyết ảnh Tà thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50610.jpg" },
            { skinName: "Chiến xa hắc ám", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50611.jpg" },
            { skinName: "Chiến xa quang minh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50612.jpg" },
            { skinName: "Liệt Hỏa Thiên Cang", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/50613.jpg" }
        ] },
    { name: "Paine", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13701.jpg", skins: [
            { skinName: "Khúc nhạc tử vong", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13701.jpg" },
            { skinName: "Phi vụ thế kỷ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13702.jpg" },
            { skinName: "Công tước máu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13703.jpg" },
            { skinName: "Ô Thước đại hiệp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13704.jpg" },
            { skinName: "Tử xà bá tước", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13705.jpg" },
            { skinName: "Megumi Fushiguro", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13706.jpg" },
            { skinName: "Cửu Đầu Tương Liễu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13707.jpg" }
        ] },
    { name: "Qi", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52801.jpg", skins: [
            { skinName: "Tiểu long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52801.jpg" },
            { skinName: "Đặc vụ cáo tuyết", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52802.jpg" },
            { skinName: "Quán quân", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52803.jpg" },
            { skinName: "Thiếu nữ pháo hoa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52804.jpg" },
            { skinName: "Blogger Ẩm thực", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52805.jpg" },
            { skinName: "Búp bê Daruma", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52806.jpg" },
            { skinName: "Thần phong Hiệp nữ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52808.jpg" },
            { skinName: "Milim Nava", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52809.jpg" },
            { skinName: "Annie Leonhart", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52810.jpg" }
        ] },
    { name: "Raz", class: "phap-su", className: "Pháp Sư/Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15702.jpg", skins: [
            { skinName: "Đại tù trưởng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15702.jpg" },
            { skinName: "Băng quyền quán quân", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15703.jpg" },
            { skinName: "Chiến thần Muay Thái", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15704.jpg" },
            { skinName: "Siêu việt", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15705.jpg" },
            { skinName: "Siêu cấp tin tặc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15706.jpg" },
            { skinName: "Saitama Cosplay", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15707.jpg" },
            { skinName: "Mãnh lôi thần quyền", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15708.jpg" },
            { skinName: "MC võ đài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15709.jpg" },
            { skinName: "Bão vũ Cuồng lôi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15710.jpg" },
            { skinName: "Gon", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15711.jpg" },
            { skinName: "Lễ hội té nước", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15712.jpg" },
            { skinName: "Đại chiến bùng nổ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15714.jpg" }
        ] },
    { name: "Ryoma", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16301.jpg", skins: [
            { skinName: "Thợ săn tiền thưởng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16301.jpg" },
            { skinName: "Đại tướng nguyệt tộc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16302.jpg" },
            { skinName: "Thanh long bang chủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16303.jpg" },
            { skinName: "Samurai huyền thoại", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16304.jpg" },
            { skinName: "Dạ hội", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16305.jpg" },
            { skinName: "Chiến binh Cyborg", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16306.jpg" },
            { skinName: "Ultraman", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16307.jpg" },
            { skinName: "Đặc nhiệm Giáng sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16308.jpg" },
            { skinName: "Khiêu chiến", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16309.jpg" },
            { skinName: "Ailing Samurai", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16310.jpg" },
            { skinName: "Maple Frost", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16311.jpg" },
            { skinName: "Thống lãnh quỷ binh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/16313.jpg" }
        ] },
    { name: "Triệu Vân", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12901.jpg", skins: [
            { skinName: "Tiến sĩ thiên tài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12901.jpg" },
            { skinName: "Đoạt mệnh thương", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12902.jpg" },
            { skinName: "Quý công tử", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12903.jpg" },
            { skinName: "Dũng sĩ đồ long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12904.jpg" },
            { skinName: "Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12905.jpg" },
            { skinName: "Chiến tướng mùa đông", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12906.jpg" },
            { skinName: "Kỵ sĩ tận thế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12907.jpg" },
            { skinName: "Cẩm y vệ: Hỏa long", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12908.jpg" },
            { skinName: "Thần tài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12910.jpg" },
            { skinName: "Minh Chung Long Đế", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12912.jpg" },
            { skinName: "Chiến Thần Vô Song", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12913.jpg" },
            { skinName: "Đấu Sĩ Võ Đài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/12914.jpg" }
        ] },
    { name: "Tulen", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19001.jpg", skins: [
            { skinName: "Nhà thám hiểm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19001.jpg" },
            { skinName: "Tân thần thiên hà", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19002.jpg" },
            { skinName: "Phù thủy kiến tạo", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19003.jpg" },
            { skinName: "Đông êm đềm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19004.jpg" },
            { skinName: "Phó kỷ luật", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19005.jpg" },
            { skinName: "Tân thần hoàng kim", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19006.jpg" },
            { skinName: "Chí tôn kiếm tiên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19007.jpg" },
            { skinName: "Dạ hội", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19008.jpg" },
            { skinName: "Thần sứ STL-79", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19009.jpg" },
            { skinName: "Hỏa thần long tộc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19010.jpg" },
            { skinName: "Đại úy Athanor", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19011.jpg" },
            { skinName: "Tân niên vệ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19012.jpg" },
            { skinName: "Tiêu Dao Vũ Thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19013.jpg" },
            { skinName: "Giám thị sấm sét", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19014.jpg" },
            { skinName: "Satoru Gojo", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19015.jpg" },
            { skinName: "Thiên Cơ Bạch Trạch", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/19016.jpg" }
        ] },
    { name: "Veera", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10901.jpg", skins: [
            { skinName: "Cô giáo hắc ám", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10901.jpg" },
            { skinName: "Góa phụ giả kim", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10902.jpg" },
            { skinName: "Nàng dơi tuyết", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10903.jpg" },
            { skinName: "Y tá bạo loạn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10904.jpg" },
            { skinName: "Thiên nga đen", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10905.jpg" },
            { skinName: "Vũ hội bóng đêm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10906.jpg" },
            { skinName: "Kimono", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10907.jpg" },
            { skinName: "Vũ điệu samba", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10908.jpg" },
            { skinName: "Đánh cắp trái tim", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10910.jpg" },
            { skinName: "Dơi hắc ám", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10911.jpg" },
            { skinName: "A.I love you", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10912.jpg" },
            { skinName: "Bách hoa tiên nữ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10913.jpg" },
            { skinName: "Phù thủy Hội họa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10914.jpg" },
            { skinName: "Thất Sát - Thượng Sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10915.jpg" },
            { skinName: "My Melody‘s Love", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10916.jpg" }
        ] },
    { name: "Veres", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52001.jpg", skins: [
            { skinName: "Đạo tặc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52001.jpg" },
            { skinName: "Gián điệp tinh hệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52002.jpg" },
            { skinName: "Thần thoại Hy Lạp", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52003.jpg" },
            { skinName: "Chị đại học đường", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52004.jpg" },
            { skinName: "Thuỷ thần kiều diễm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52006.jpg" },
            { skinName: "Kimono", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52007.jpg" },
            { skinName: "Phù thủy trang điểm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52008.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52009.jpg" },
            { skinName: "Men Lam Hồn Gốm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52010.jpg" },
            { skinName: "Lưu Ly Long Mẫu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52011.jpg" },
            { skinName: "Vũ điệu dân gian", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52012.jpg" },
            { skinName: "Thỏ may mắn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52013.jpg" },
            { skinName: "Idol Giáng Sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52014.jpg" },
            { skinName: "Hoa Khôi Khán Đài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52015.jpg" }
        ] },
    { name: "Violet", class: "xa-thu", className: "Xạ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11101.jpg", skins: [
            { skinName: "Nữ hoàng pháo hoa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11101.jpg" },
            { skinName: "Nữ đặc cảnh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11102.jpg" },
            { skinName: "Phi công trẻ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11103.jpg" },
            { skinName: "Mèo siêu quậy", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11104.jpg" },
            { skinName: "Tiệc bãi biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11105.jpg" },
            { skinName: "Phó học tập", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11106.jpg" },
            { skinName: "Thứ nguyên vệ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11107.jpg" },
            { skinName: "Pháo hoa Neon", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11108.jpg" },
            { skinName: "Đặc dị", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11109.jpg" },
            { skinName: "Vợ người ta", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11110.jpg" },
            { skinName: "Tay súng siêu phàm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11111.jpg" },
            { skinName: "Huy chương vàng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11112.jpg" },
            { skinName: "Huyết ma thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11113.jpg" },
            { skinName: "Lam tước", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11114.jpg" },
            { skinName: "Thần Long tỷ tỷ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11115.jpg" },
            { skinName: "DJ Câu hồn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11116.jpg" },
            { skinName: "Hoa thủy tiên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11117.jpg" },
            { skinName: "Vọng nguyệt Long Cơ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11119.jpg" },
            { skinName: "Nobara Kugisaki", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11120.jpg" },
            { skinName: "Nữ quản thú", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/11121.jpg" }
        ] },
    { name: "Volkath", class: "dau-si", className: "Đấu Sĩ/Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52901.jpg", skins: [
            { skinName: "Dạ huyết tộc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52901.jpg" },
            { skinName: "Ma kỵ tử sĩ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52902.jpg" },
            { skinName: "Xung thiên thần tướng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52903.jpg" },
            { skinName: "Tư lệnh viễn chinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52904.jpg" },
            { skinName: "Chiến thần Ai Cập", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52905.jpg" },
            { skinName: "Hắc kỵ thời không", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52906.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52907.jpg" },
            { skinName: "Ma Ảnh Thần Đao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/52908.jpg" }
        ] },
    { name: "Yan", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54401.jpg", skins: [
            { skinName: "Nhà chế tác", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54401.jpg" },
            { skinName: "Tanjiro Kamado", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54402.jpg" },
            { skinName: "Công tước Norman", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54403.jpg" },
            { skinName: "Giấc mơ sao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54404.jpg" },
            { skinName: "Bích Hạc Phiên Vân", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54405.jpg" },
            { skinName: "Nghệ nhân Trung Thu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/54406.jpg" }
        ] },
    { name: "Yena", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15401.jpg", skins: [
            { skinName: "Khuyên bạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15401.jpg" },
            { skinName: "Thỏ may mắn", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15402.jpg" },
            { skinName: "Chiến binh nguyệt tộc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15403.jpg" },
            { skinName: "Hoạt náo viên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15404.jpg" },
            { skinName: "Nữ hoàng thể thao", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15405.jpg" },
            { skinName: "Dạ nguyệt thánh nữ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15406.jpg" },
            { skinName: "Giảng viên tình ái", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15407.jpg" },
            { skinName: "Nữ cướp biển", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15408.jpg" },
            { skinName: "WaVe", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15409.jpg" },
            { skinName: "Vũ điệu Giáng Sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15410.jpg" },
            { skinName: "Huyền Cửu Thiên", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15412.jpg" },
            { skinName: "Trấn Yêu Thần Lộc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15413.jpg" },
            { skinName: "Thần Sứ kiều diễm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15414.jpg" },
            { skinName: "Hoa tiêu Mộng giới", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/15415.jpg" }
        ] },
    { name: "Zata", class: "phap-su", className: "Pháp Sư", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51301.jpg", skins: [
            { skinName: "Tư lệnh viễn chinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51301.jpg" },
            { skinName: "Sứ giả tinh hệ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51302.jpg" },
            { skinName: "Thần mặt trời", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51303.jpg" },
            { skinName: "Khiêu chiến", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51304.jpg" },
            { skinName: "Tác gia đương đại", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51305.jpg" },
            { skinName: "Chí tôn Tà phượng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51306.jpg" },
            { skinName: "Xích Huyết Bá Tước", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51307.jpg" },
            { skinName: "Idol Giáng Sinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/51308.jpg" }
        ] },
    { name: "Zephys", class: "dau-si", className: "Đấu Sĩ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10701.jpg", skins: [
            { skinName: "Oán linh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10701.jpg" },
            { skinName: "Hiệp sĩ bí ngô", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10703.jpg" },
            { skinName: "Dung nham", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10704.jpg" },
            { skinName: "Siêu việt", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10705.jpg" },
            { skinName: "Phi thương", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10706.jpg" },
            { skinName: "Tư lệnh viễn chinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10707.jpg" },
            { skinName: "Hắc vô thường", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10708.jpg" },
            { skinName: "Inosuke Hashibira", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10709.jpg" },
            { skinName: "Đầu bếp Sashimi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10711.jpg" },
            { skinName: "Nghệ nhân đồ chơi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10712.jpg" },
            { skinName: "Kỷ Nguyên Hổ Phách", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10714.jpg" },
            { skinName: "Chị đại Gangster", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/10715.jpg" }
        ] },
    { name: "Sinestrea", class: "sat-thu", className: "Sát Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53501.jpg", skins: [
            { skinName: "Giấc mơ trưa", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53501.jpg" },
            { skinName: "Tiểu thư Băng giá", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53502.jpg" },
            { skinName: "WaVe", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53503.jpg" },
            { skinName: "Điệp viên cánh cụt", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53504.jpg" },
            { skinName: "Đại tiểu thư", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53507.jpg" },
            { skinName: "Tiểu thư bóng đêm", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53508.jpg" },
            { skinName: "Lữ khách sa mạc", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53509.jpg" },
            { skinName: "Giấc mộng biển xanh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53510.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53511.jpg" },
            { skinName: "Nữ quỷ say ngủ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53512.jpg" },
            { skinName: "Định Vị Tuyệt Đối", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/53513.jpg" }
        ] },
    { name: "Valhein", class: "xa-thu", className: "Xạ Thủ", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13301.jpg", skins: [
            { skinName: "Hoàng tử quạ", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13301.jpg" },
            { skinName: "Vũ khí tối thượng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13302.jpg" },
            { skinName: "Đại công tước", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13304.jpg" },
            { skinName: "Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13305.jpg" },
            { skinName: "Số 7 thần sầu", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13306.jpg" },
            { skinName: "Khiêu chiến", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13307.jpg" },
            { skinName: "Cá mập \"nghiêm túc\"", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13308.jpg" },
            { skinName: "Hoàng tử Băng", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13309.jpg" },
            { skinName: "Thần tài", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13310.jpg" },
            { skinName: "Xạ thần Kagutsuchi", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13311.jpg" },
            { skinName: "S - Quang vinh", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13312.jpg" },
            { skinName: "Đệ nhất thần thám", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13313.jpg" },
            { skinName: "Thứ nguyên vệ thần", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13314.jpg" },
            { skinName: "Mã Hành Vạn Lý", downloadLink: "#", img: "https://dl.ops.kgtw.garenanow.com/CHT/HeroTrainingLoadingNew_B36/13316.jpg" }
        ] }
];
